### ISSUE TITLE
Adding the Navigation Bar

### ISSUE THREAD

**Issue by VitthalGund** [DiplomaTechCommunity/DTC-Archive#10]
## Navigation Bar
we can add a navigation bar to the Project-Vault Website containing the following links:

1. Different Social Media Handles of DTC
2. DTC Main website

**Comment by CODEX108** [comment]
@VitthalGund We appreciate your suggestion, and we have addressed this matter in the following issue.
https://github.com/DiplomaTechCommunity/Project-Vault/issues/18
