### ISSUE TITLE
Feat : Adding Home Page along with all the functionalities

### ISSUE THREAD

**Issue by CODEX108** [DiplomaTechCommunity/DTC-Archive#18]
### 1. Design and Content from Figma:

- Refer to the Figma design file for the visual layout, colors, typography, and content arrangement.
Pay close attention to spacing, alignment, and any visual elements presented in the design.
Component Bifurcation:

- Divide the webpage into separate components to ensure clarity and avoid confusion during development.
Identify components such as Navbar, Hero section, Why Does It Matter section, and Footer section.

### 2.Navbar & Footer component.
- Implement the design of the footer with appropriate content, links, and any other information required.
Ensure that footer links are working correctly and lead to relevant pages or external sites.
Hero Section Component:

- HeroSection.
Implement the design of the hero section with the main heading, subheading, and any accompanying visual elements.
Make sure the hero section content is responsive and adjusts well on different screen sizes.
Why Does It Matter Section Component:

- Why Matter Section. (add a suitable name)
Implement the design of the "Why Does It Matter" section, including headings, content, and any images or icons.
Ensure that the section's content is responsive and maintains its layout on various devices.
Responsive Design:

- Use CSS media queries to adjust styles, layout, and spacing as the screen size changes.
File Naming Conventions:

>Follow a consistent and clear file naming convention for your components, styles, and other assets.
>Create separate files for each component to keep your code organized and maintainable.

**Comment by DrasticCoder** [comment]
Could anyone assist me by providing the Figma design file link that was mentioned by @CODEX108 ?

**Comment by CODEX108** [comment]
https://www.figma.com/file/GAPUlc2xXIytWLRp7WewSM/Project-Vault?type=design&node-id=1%3A2&mode=design&t=jlUMaHDNk658cFyC-1

**Comment by DrasticCoder** [comment]
> https://www.figma.com/file/GAPUlc2xXIytWLRp7WewSM/Project-Vault?type=design&node-id=1%3A2&mode=design&t=jlUMaHDNk658cFyC-1

Thank you

**Comment by CODEX108** [comment]
@DrasticCoder make sure to inform us if you wish to take the task.

**Comment by DrasticCoder** [comment]
Sure, I'm interested in taking on the task. Please provide me with more details about the task so I can better understand what's involved. Thank you!

**Comment by anaskhan28** [comment]
yeah sure but I have something more interesting for you.. 😶‍🌫️

**Comment by DrasticCoder** [comment]
> yeah sure but I have something more interesting for you.. 😶‍🌫️

I appreciate your consideration! I'm definitely intrigued to hear about the more interesting task you have in mind. Please feel free to share the details, and I'm open to discussing how I can contribute effectively. 😊🌟
