### ISSUE TITLE
Better Search.

### ISSUE THREAD

**Issue by maaz25925** [DiplomaTechCommunity/DTC-Archive#24]
The search bar finds the projects by a perfectly matching string and the output is affected by white-space.

When you search for the project name **as it is**, it works perfectly fine.

---

Example 1:

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/ccc1a098-adfa-4db5-a36b-cd62e22631d1)

Example 2:

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/781c93e2-b92b-485b-9db0-373946c2157c)

---

But when I type in:

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/f296a71f-1a5b-4214-a258-0a7f84614152)

And what if I do this:

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/a89f158d-9a2f-4eb7-a8ae-b6279d955225)

---

I hope the problem is clear through the images and search queries.

What I would suggest to fix this is when processing the search query of the user, remove the white-spaces as well as remove the white-spaces of the project titles.

The removal of white-spaces would only be when the process of cross-checking would be there and otherwise they can be stored normally as they are.

Now I understand that the code behind the scenes searches in project name, description and tech stack used which is why this is a suggestion.

**Comment by CODEX108** [comment]
I can try to fix this

**Comment by maaz25925** [comment]
I made an attempt: https://github.com/maaz25925/DTC-Archive/commit/e3706d3cfbabd808664a4dc237e84fc1deb717c7.

@CODEX108 please see if it's working and whether I should make a pull request.

Here are two screenshots:

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/2023751e-5dae-4d3a-a254-3674920a2fa2)

![image](https://github.com/DiplomaTechCommunity/Project-Vault/assets/96342418/afed9928-aa99-4c74-8c69-597034dde068)

**Comment by CODEX108** [comment]
Raise a PR separately for the search functionality issue
